DROP TABLE IF EXISTS WATCHER;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS REQUEST;
DROP TABLE IF EXISTS USER;


CREATE TABLE USER (
       ID INT NOT NULL AUTO_INCREMENT
     , USERNAME VARCHAR(50)
     , ENABLED BOOLEAN
     , PRIMARY KEY (ID)
);

CREATE TABLE ROLE (
       ID INT NOT NULL  AUTO_INCREMENT
     , USER_ID INT
     , ROLE VARCHAR(32)
     , PRIMARY KEY (ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID)
                  REFERENCES USER (ID)
);

CREATE TABLE REQUEST (
       ID INT NOT NULL AUTO_INCREMENT
     , TYPE INT
     , TITLE VARCHAR(200) NOT NULL
     , CONTENT VARCHAR(4000)
     , STARTDATE DATETIME
     , ENDATE DATETIME
     , ASSIGNED_ID INT
     , ASSIGNED_ACCOUNT CHAR(50)
     , ASSIGNED_NAME CHAR(100)
     , WATCHERS INT
     , MANAGER_ID INT
     , MANAGER_ACCOUNT VARCHAR(50)
     , MANAGER_NAME VARCHAR(100)
     , STATUS VARCHAR(30)
     , ATTACHMENT1 BLOB
     , ATTACHMENT2 BLOB
     , ATTACHMENT3 BLOB
     , CREATED DATETIME NOT NULL
     , CREATEDBY_ID INT
     , CREATEDBY_ACCOUNT VARCHAR(50)
     , CREATEDBY_NAME VARCHAR(100)
     , LASTMODIFIED DATETIME
     , LASTMODIFIEDBY_ID INT
     , LASTMODIFIEDBY_NAME VARCHAR(100)
     , LASTMODIFIEDBY_ACCOUNT VARCHAR(50)
     , PRIMARY KEY (ID)
     , INDEX (ASSIGNED_ID)
     , CONSTRAINT FK_REQUEST_USER FOREIGN KEY (ASSIGNED_ID)
                  REFERENCES USER (ID)
     , INDEX (MANAGER_ID)
     , CONSTRAINT FK_REQUEST_USER_MANAGER FOREIGN KEY (MANAGER_ID)
                  REFERENCES USER (ID)
     , INDEX (CREATEDBY_ID)
     , CONSTRAINT FK_REQUEST_USER_CREATEDBY FOREIGN KEY (CREATEDBY_ID)
                  REFERENCES USER (ID)
);


CREATE TABLE WATCHER (
       ID INT NOT NULL  AUTO_INCREMENT
     , REQ_ID INT NOT NULL
     , USER_ID INT
     , USER_ACCOUNT VARCHAR(50)
     , USER_NAME VARCHAR(100)
     , PRIMARY KEY (ID)
     , INDEX (REQ_ID)
     , CONSTRAINT FK_WATCHER_REQUEST FOREIGN KEY (REQ_ID)
                  REFERENCES REQUEST (ID)
     , INDEX (USER_ID)
     , CONSTRAINT FK_WATCHER_USER FOREIGN KEY (USER_ID)
                  REFERENCES USER (ID)
);

